org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=1024m
org.gradle.java.installations.auto-download=false
android.useAndroidX=true
android.enablePngCrunchInReleaseBuilds=true
android.enableProguardInReleaseBuilds=true
android.enableShrinkResourcesInReleaseBuilds=true
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
newArchEnabled=true
hermesEnabled=true
expo.gif.enabled=false
expo.webp.enabled=false
expo.webp.animated=false
EX_DEV_CLIENT_NETWORK_INSPECTOR=true
expo.useLegacyPackaging=false
